package com.quakd.web.model;

// Generated Jan 25, 2014 11:00:46 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyQponds generated by hbm2java
 */
@Entity
@Table(name = "company_qponds", catalog = "quser")
public class CompanyQponds implements java.io.Serializable {

	private Long qid;
	private CompanyInformation companyInformation;
	private String desc;
	private byte[] img;
	private String imgType;
	private String optionalCd;
	private Date createdDt;
	private Integer weight;
	private String shared;
	private Set<MemberQuaks> memberQuakses = new HashSet<MemberQuaks>(0);

	public CompanyQponds() {
	}

	public CompanyQponds(CompanyInformation companyInformation) {
		this.companyInformation = companyInformation;
	}

	public CompanyQponds(CompanyInformation companyInformation, String desc,
			byte[] img, String imgType, String optionalCd, Date createdDt,
			Integer weight, String shared, Set<MemberQuaks> memberQuakses) {
		this.companyInformation = companyInformation;
		this.desc = desc;
		this.img = img;
		this.imgType = imgType;
		this.optionalCd = optionalCd;
		this.createdDt = createdDt;
		this.weight = weight;
		this.shared = shared;
		this.memberQuakses = memberQuakses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "qid", unique = true, nullable = false)
	public Long getQid() {
		return this.qid;
	}

	public void setQid(Long qid) {
		this.qid = qid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_cd", nullable = false)
	public CompanyInformation getCompanyInformation() {
		return this.companyInformation;
	}

	public void setCompanyInformation(CompanyInformation companyInformation) {
		this.companyInformation = companyInformation;
	}

	@Column(name = "desc", length = 65535)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "img")
	public byte[] getImg() {
		return this.img;
	}

	public void setImg(byte[] img) {
		this.img = img;
	}

	@Column(name = "img_type", length = 100)
	public String getImgType() {
		return this.imgType;
	}

	public void setImgType(String imgType) {
		this.imgType = imgType;
	}

	@Column(name = "optional_cd", length = 50)
	public String getOptionalCd() {
		return this.optionalCd;
	}

	public void setOptionalCd(String optionalCd) {
		this.optionalCd = optionalCd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_dt", length = 10)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "shared", length = 1)
	public String getShared() {
		return this.shared;
	}

	public void setShared(String shared) {
		this.shared = shared;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyQponds")
	public Set<MemberQuaks> getMemberQuakses() {
		return this.memberQuakses;
	}

	public void setMemberQuakses(Set<MemberQuaks> memberQuakses) {
		this.memberQuakses = memberQuakses;
	}

}
