package com.quakd.web.model;

// Generated Jan 5, 2014 9:49:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CompanyBilling generated by hbm2java
 */
@Entity
@Table(name = "company_billing", catalog = "quser", uniqueConstraints = @UniqueConstraint(columnNames = "COMPANY_CD"))
public class CompanyBilling implements java.io.Serializable {

	private Long billingId;
	private CompanyInformation companyInformation;
	private Country country;
	private UsStates usStates;
	private String address;
	private String city;
	private String zip;
	private byte[] ccNum;
	private String ccSCode;
	private String rtNum;
	private String actNum;
	private Date modifiedDt;

	public CompanyBilling() {
	}

	public CompanyBilling(CompanyInformation companyInformation,
			Country country, String address, String city, String zip) {
		this.companyInformation = companyInformation;
		this.country = country;
		this.address = address;
		this.city = city;
		this.zip = zip;
	}

	public CompanyBilling(CompanyInformation companyInformation,
			Country country, UsStates usStates, String address, String city,
			String zip, byte[] ccNum, String ccSCode, String rtNum,
			String actNum, Date modifiedDt) {
		this.companyInformation = companyInformation;
		this.country = country;
		this.usStates = usStates;
		this.address = address;
		this.city = city;
		this.zip = zip;
		this.ccNum = ccNum;
		this.ccSCode = ccSCode;
		this.rtNum = rtNum;
		this.actNum = actNum;
		this.modifiedDt = modifiedDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BILLING_ID", unique = true, nullable = false)
	public Long getBillingId() {
		return this.billingId;
	}

	public void setBillingId(Long billingId) {
		this.billingId = billingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_CD", unique = true, nullable = false)
	public CompanyInformation getCompanyInformation() {
		return this.companyInformation;
	}

	public void setCompanyInformation(CompanyInformation companyInformation) {
		this.companyInformation = companyInformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CD", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_CD")
	public UsStates getUsStates() {
		return this.usStates;
	}

	public void setUsStates(UsStates usStates) {
		this.usStates = usStates;
	}

	@Column(name = "ADDRESS", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "CC_NUM")
	public byte[] getCcNum() {
		return this.ccNum;
	}

	public void setCcNum(byte[] ccNum) {
		this.ccNum = ccNum;
	}

	@Column(name = "CC_S_CODE", length = 4)
	public String getCcSCode() {
		return this.ccSCode;
	}

	public void setCcSCode(String ccSCode) {
		this.ccSCode = ccSCode;
	}

	@Column(name = "RT_NUM", length = 45)
	public String getRtNum() {
		return this.rtNum;
	}

	public void setRtNum(String rtNum) {
		this.rtNum = rtNum;
	}

	@Column(name = "ACT_NUM", length = 45)
	public String getActNum() {
		return this.actNum;
	}

	public void setActNum(String actNum) {
		this.actNum = actNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

}
