package com.quakd.web.model;

// Generated Jun 17, 2014 10:44:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompanyMessage generated by hbm2java
 */
@Entity
@Table(name = "company_message", catalog = "quser")
public class CompanyMessage implements java.io.Serializable {

	private Integer messageId;
	private CompanyInformation companyInformation;
	private String message;

	public CompanyMessage() {
	}

	public CompanyMessage(CompanyInformation companyInformation, String message) {
		this.companyInformation = companyInformation;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MESSAGE_ID", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_CD", nullable = false)
	public CompanyInformation getCompanyInformation() {
		return this.companyInformation;
	}

	public void setCompanyInformation(CompanyInformation companyInformation) {
		this.companyInformation = companyInformation;
	}

	@Column(name = "MESSAGE", nullable = false, length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
