package com.quakd.web.model;

// Generated Jan 5, 2014 9:49:17 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.quakd.web.data.EmailBean;

/**
 * EmailQueue generated by hbm2java
 */
@Entity
@Table(name = "email_queue", catalog = "quser")
public class EmailQueue implements java.io.Serializable {

	private Integer emailId;
	private String userType;
	private byte[] emailTxt;
	private String emailSubject;
	private String emailFrom;
	private String emailTo;
	private Date emailSentDt;
	private Date emailCreatedDt;
	private String processed;
	
	public EmailQueue(EmailBean bean)
	{
		setEmailFrom(bean.getFrom());
		setEmailSubject(bean.getSubject());
		setEmailTo(bean.getTo());
		setUserType(bean.getUserType().toString());
		setEmailTxt(bean.getBodyText().getBytes());
	}

	public EmailQueue() {
	}

	public EmailQueue(String userType, byte[] emailTxt,
			String emailSubject, String emailFrom, String emailTo,
			Date emailCreatedDt, String processed) {
		this.userType = userType;
		this.emailTxt = emailTxt;
		this.emailSubject = emailSubject;
		this.emailFrom = emailFrom;
		this.emailTo = emailTo;
		this.emailCreatedDt = emailCreatedDt;
		this.processed = processed;
	}

	public EmailQueue(String userType, byte[] emailTxt,
			String emailSubject, String emailFrom, String emailTo,
			Date emailSentDt, Date emailCreatedDt, String processed) {
		this.userType = userType;
		this.emailTxt = emailTxt;
		this.emailSubject = emailSubject;
		this.emailFrom = emailFrom;
		this.emailTo = emailTo;
		this.emailSentDt = emailSentDt;
		this.emailCreatedDt = emailCreatedDt;
		this.processed = processed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMAIL_ID", unique = true, nullable = false)
	public Integer getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 1)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "EMAIL_TXT", nullable = false)
	public byte[] getEmailTxt() {
		return this.emailTxt;
	}

	public void setEmailTxt(byte[] emailTxt) {
		this.emailTxt = emailTxt;
	}

	@Column(name = "EMAIL_SUBJECT", nullable = false, length = 1000)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "EMAIL_FROM", nullable = false, length = 200)
	public String getEmailFrom() {
		return this.emailFrom;
	}

	public void setEmailFrom(String emailFrom) {
		this.emailFrom = emailFrom;
	}

	@Column(name = "EMAIL_TO", nullable = false, length = 200)
	public String getEmailTo() {
		return this.emailTo;
	}

	public void setEmailTo(String emailTo) {
		this.emailTo = emailTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EMAIL_SENT_DT", length = 19)
	public Date getEmailSentDt() {
		return this.emailSentDt;
	}

	public void setEmailSentDt(Date emailSentDt) {
		this.emailSentDt = emailSentDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EMAIL_CREATED_DT", nullable = false, length = 19)
	public Date getEmailCreatedDt() {
		return this.emailCreatedDt;
	}

	public void setEmailCreatedDt(Date emailCreatedDt) {
		this.emailCreatedDt = emailCreatedDt;
	}

	@Column(name = "PROCESSED", nullable = false, length = 1)
	public String getProcessed() {
		return this.processed;
	}

	public void setProcessed(String processed) {
		this.processed = processed;
	}

}
