package com.quakd.web.model;

// Generated Jan 25, 2014 12:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberQuaks generated by hbm2java
 */
@Entity
@Table(name = "member_quaks", catalog = "quser")
public class MemberQuaks implements java.io.Serializable {

	private Long quakid;
	private Member member;
	private CompanyLocation companyLocation;
	private CompanyQponds companyQponds;
	private String link;
	private String sharedOn;
	private String message;
	private Date createdDt;
	private Set<MemberQidRedeem> memberQidRedeems = new HashSet<MemberQidRedeem>(
			0);

	public MemberQuaks() {
	}

	public MemberQuaks(Member member, CompanyLocation companyLocation,
			CompanyQponds companyQponds, String link, String sharedOn,
			String message) {
		this.member = member;
		this.companyLocation = companyLocation;
		this.companyQponds = companyQponds;
		this.link = link;
		this.sharedOn = sharedOn;
		this.message = message;
	}

	public MemberQuaks(Member member, CompanyLocation companyLocation,
			CompanyQponds companyQponds, String link, String sharedOn,
			String message, Date createdDt,
			Set<MemberQidRedeem> memberQidRedeems) {
		this.member = member;
		this.companyLocation = companyLocation;
		this.companyQponds = companyQponds;
		this.link = link;
		this.sharedOn = sharedOn;
		this.message = message;
		this.createdDt = createdDt;
		this.memberQidRedeems = memberQidRedeems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "quakid", unique = true, nullable = false)
	public Long getQuakid() {
		return this.quakid;
	}

	public void setQuakid(Long quakid) {
		this.quakid = quakid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loc_id", nullable = false)
	public CompanyLocation getCompanyLocation() {
		return this.companyLocation;
	}

	public void setCompanyLocation(CompanyLocation companyLocation) {
		this.companyLocation = companyLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qid", nullable = false)
	public CompanyQponds getCompanyQponds() {
		return this.companyQponds;
	}

	public void setCompanyQponds(CompanyQponds companyQponds) {
		this.companyQponds = companyQponds;
	}

	@Column(name = "link", nullable = false, length = 500)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "shared_on", nullable = false, length = 1)
	public String getSharedOn() {
		return this.sharedOn;
	}

	public void setSharedOn(String sharedOn) {
		this.sharedOn = sharedOn;
	}

	@Column(name = "message", nullable = false, length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_dt", length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberQuaks")
	public Set<MemberQidRedeem> getMemberQidRedeems() {
		return this.memberQidRedeems;
	}

	public void setMemberQidRedeems(Set<MemberQidRedeem> memberQidRedeems) {
		this.memberQidRedeems = memberQidRedeems;
	}

}
