package com.quakd.web.model;

// Generated Jan 6, 2014 8:21:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberRoles generated by hbm2java
 */
@Entity
@Table(name = "member_roles", catalog = "quser")
public class MemberRoles implements java.io.Serializable {

	private Long roleId;
	private CompanyInformation companyInformation;
	private Member member;
	private CompanyLocation companyLocation;
	private String roleName;
	private Date grantedDt;

	public MemberRoles() {
	}

	public MemberRoles(Member member, String roleName, Date grantedDt) {
		this.member = member;
		this.roleName = roleName;
		this.grantedDt = grantedDt;
	}

	public MemberRoles(CompanyInformation companyInformation, Member member,
			CompanyLocation companyLocation, String roleName, Date grantedDt) {
		this.companyInformation = companyInformation;
		this.member = member;
		this.companyLocation = companyLocation;
		this.roleName = roleName;
		this.grantedDt = grantedDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_CD")
	public CompanyInformation getCompanyInformation() {
		return this.companyInformation;
	}

	public void setCompanyInformation(CompanyInformation companyInformation) {
		this.companyInformation = companyInformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEMBER_ID", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID")
	public CompanyLocation getCompanyLocation() {
		return this.companyLocation;
	}

	public void setCompanyLocation(CompanyLocation companyLocation) {
		this.companyLocation = companyLocation;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRANTED_DT", nullable = false, length = 19)
	public Date getGrantedDt() {
		return this.grantedDt;
	}

	public void setGrantedDt(Date grantedDt) {
		this.grantedDt = grantedDt;
	}

}
